---
- name: EPM repos
  yum_repository: name={{item.name}} description='{{item.desc}}' baseurl=http://epm.ebi.ac.uk/epm/baselines/{{item.epm}} gpgcheck=no state=present owner=root group=root mode=0644
  with_items:
    - {name: rhel-7-server-rpms, desc: 'RHEL Server 7 x86_64', epm: rh7-network/rhel-7-server-rpms}
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7
